run:
  timeout: 2m # increased timeout for running check on Windows in GitHub Actions
linters:
  enable:
    - bodyclose
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gosec
    - misspell
    - nakedret
    - nestif
    - prealloc
    - unconvert
    - unparam
    - wsl
