on: [pull_request]
name: Check
jobs:
  check:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.0
      - name: Test
        run: go test -v ./...
