on: [pull_request]
name: Check
jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: [1.23.x, 1.24.x, 1.25.0-rc.2]
    continue-on-error: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.0
      - name: Test
        run: go test -v ./...
